### ISSUE TITLE
Computation of error metrics

### ISSUE THREAD

**Issue by yewzijian** [xiangruhuang/Learning2Sync#1]
Hi,

I would like to confirm whether my understanding of the error metrics computation reported in Figure 4 is correct. Specifically are the following correct?

- Each ScanNet scene contains 100 frames. This means there are 100C2=4950 relative poses between all pairs of frames. Are the metrics computed on all 4950 such frames for each scene?
- The rotation error is computed using arccos(0.5 * (tr(R^T_ij R*_ij)-1)), and the translation error is the l2 norm of t_ij - t*_ij ?
- Then the ECDF plots are the percentage of the all pairs which have the rotation/translation errors below a specific threshold?

I'm asking because after I used the provided source code to generate the data, the input statistics of the test scenes, i.e. row 1 - FastGR(all) is different from that reported in the paper. Would like to check where my error is.

Thank you.

Zi Jian

**Comment by xiangruhuang** [comment]
Hi Zi Jian,

Happy to hear that you’re interested in reproducing our result!

For bullet point 1, the number of frames are less relevant than how you
sample the frames in the video. For the paper, I sampled 30~50 frames for
each scene where each pair of consecutive sampled frames are 30 frames away
in the original video. The sampling strategy is also explained in the
paper, you can check it out.

For the second bullet point, yes.

For the third bullet point, what do you mean by ECDF? Can you be more
specific?

Another important factor is the parameter of FastGR algorithm, please refer
to my source code.

Could you be more specific on what error distribution you got and how you
sample the frames? I’m happy to help.

Best,
Xiangru

**Comment by yewzijian** [comment]
Hi Xiangru, thanks for the reply. 

Sorry I actually meant CDF. The term ECDF was used in Zan Gojcic's "Learning Multiview 3D point cloud registration", but I guess they mean the same thing.

I used your source codes to preprocess and compute the relative poses of the ScanNet dataset. Specifically, I ran for the ScanNet dataset:

1. `src/data_processing/process_scannet.py`
2. `src/relative_pose_estimation/FastGlobalRegistration/generate_tasks.py` and executed the generated tasks
3. `src/relative_pose_estimation/summarize.py`

I noticed that the above codes extracts 100 frames from each ScanNet scenes, as defined in line 146 of `src/data_processing/process_scannet.py`, each around ~6 frames apart (line 155 of `src/data_processing/process_scannet.py`). I didn't change the source codes, although I modified the scene list to follow the scenes listed in Figure 10 of the paper appendix.

After obtaining the summary .mat files, I computed the errors for the 32 test scenes by comparing the 32*4950 pairwise transforms. However I get quite different values. My FastGR(all) results looks like the following for the CDF and mean errors.

Rot CDF: 20.7 (3), 22.2 (5), 24.9 (10), 33.0 (30), 37.9 (45) | 77.40 (mean)
Trans CDF: 15.8 (0.05), 17.9 (0.1), 22.1 (0.25), 28.8 (0.5), 35.6 (0.75) | 1.57 (mean)

My mean errors are comparable with that reported in the paper, yet the CDF percentages are quite a bit higher.


Regards,
Zi Jian

**Comment by xiangruhuang** [comment]
So the code on the GitHub should reproduce the processing algorithm but
there are some parameters changed (as I tried to perform another set of
experiment that has denser frames and forgot to change them back). If
you’re willing to get the exact error distribution, please refer to the
paper for these parameters (e.g., in the paper there are 30 frames frames
that are 20 frames away from each other).

This looks reasonable to me: your frames are closer to each other in the
video and thus you have higher fraction of good relative transformations.

Xiangru

**Comment by yewzijian** [comment]
I see, ok, thanks for the clarification!

Regards,
Zi Jian

**Comment by yewzijian** [comment]
I see from the paper Section 5.1 that this is mentioned for Redwood dataset but not ScanNet. Can I confirm that this 30 frames at 20 frame interval is also used for ScanNet? 

Zi Jian

**Comment by xiangruhuang** [comment]
Yes.
